### PR TITLE
minor tweaks to db setup script and updated readme

### PR DESCRIPTION
**Pull request by jjshanks**
When I tried to run the setup script locally I kept getting the following error:

> ERROR 1067 (42000) at line 145: Invalid default value for 'expenditure_date'

Unless expenditure_date needs to also track time a DATE would be better, otherwise it should probably be a DATETIME instead of a timestamp.

### CODE REVIEW

**Comment by nsudarsanam** [comment]
Interesting..yeah I ran into that too, I was waiting to see if anyone else sees it. I think its because of the mysql edition potentially. I switched it to be null default null and that seemed to work.

**Comment by jjshanks** [comment]
@nsudarsanam I updated it to null default null and that seemed to work. I still think DATE or DATETIME would be a better type but leaving for now.

**Comment by LinneaHarts** [comment]
I'll update the database create scripts. Soon they will just be "alters" but with the db empty, I'm still futzing with creation scripts.

**Comment by LinneaHarts** [comment]
Can someone please fix the Readme conflicts? Thanks.

**Comment by nsudarsanam** [comment]
Looks like this pr isn't needed any more since your subsequent PR fixes the type to date? 
Re: conflicts in readme, the merge-squash should fix it automatically (i.e. git will resolve it or you can manually resolve when merging into master).

**Pull request merged**
